### ISSUE TITLE
Might you developing a base 36 version?

### ISSUE THREAD

**Issue by serrq** [cyb3rko/pincredible#10]
It will be interesting if I might print on paper (from a previously generated pdf file) a vault password to bring with me during a trip or to safely store at home.

If a dictatorship's police or any aggressive entity find it, it can only read numbers and characters without any sense.

0 ~ 9
A ~ Z (uppercase)

**Comment by cyb3rko** [comment]
Good idea for a new app.

1. Please open a new issue for that here: [cyb3rko/backpack-apps](https://github.com/cyb3rko/backpack-apps)
2. I'm working on the base structure for the backpack-apps. Once finished I can start working on other similiar apps.
3. Why only base36? Because you couldn't save special characters like # or . right? I think the easiest choice is just using a standard char.

**Comment by cyb3rko** [comment]
Oh okay.
Are the shown numbers an example? I could not extract data from that example.
