### ISSUE TITLE
Improve save dialog 

### ISSUE THREAD

**Issue by johnjohndoe** [cyb3rko/pincredible#18]
I noticed the following issues:
- closes on rotation
- does not respect the character limit
- does not show an error message on reaching the character limit

**Comment by cyb3rko** [comment]
Thank you for your feedback.

Which save dialog are you referring to?
The password input dialog for backups or the dialog when saving the PIN table as image?

**Comment by johnjohndoe** [comment]
I was referring to the "Save PIN" dialog but it is probably good to check all dialogs.

**Comment by cyb3rko** [comment]
Which version did you use?

Because for me it works as expected and as defined by Material 3 (using Version 0.4.1):

When typing and exceeding the limit the box and character limit color turns red.

<Img src="https://user-images.githubusercontent.com/46033730/222931829-1943ae02-bf76-4080-810d-63b0f36d0b94.png" width="400">

If I click on "Save" an additional error message is shown.

<Img src="https://user-images.githubusercontent.com/46033730/222931855-81cf2855-2383-4132-8b70-004d465910ae.png" width="400">

**Comment by johnjohndoe** [comment]
Ah. My expectation would be that characters more than 30 are not accepted and the error shows up immediately when I type 30+ characters.
